name: mdns_bloc
description: Bloc wrapper over 'multicast_dns' which performs service discovery over multicast DNS (mDNS), Bonjour and Avahi.
version: 0.1.0
repository: https://github.com/alanmosely/mdns_bloc
issue_tracker: https://github.com/alanmosely/mdns_bloc/issues
topics:
  - mdns
  - bonjour
  - avahi
  - bloc
  - service-discovery

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  multicast_dns: ^0.3.2+4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
